version: '3'

services:
  drupal:
    image: drupal
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: admin